site_name: ft_badges
site_url: https://airone01.github.io/ft_badges
repo_url: https://github.com/airone01/ft_badges
repo_name: airone01/ft_badges
theme:
  name: shadcn
  icon: lucide:award

docs_dir: docs_src
site_dir: docs

markdown_extensions:
  - codehilite
  - md_in_html
  - admonition

nav:
  - Home: index.md
  - Usage Guide: usage.md
  - Projects:
    - Bord2beroot: projects/born2beroot.md
    - cub3d: projects/cub3d.md
    - FdF: projects/fdf.md
    - fract-ol: projects/fract-ol.md
    - ft_irc: projects/ft_irc.md
    - ft_printf: projects/ft_printf.md
    - ft_transcendence: projects/ft_transcendence.md
    - get_next_line: projects/get_next_line.md
    - Inception: projects/inception.md
    - Libft: projects/libft.md
    - miniRT: projects/minirt.md
    - minishell: projects/minishell.md
    - minitalk: projects/minitalk.md
    - NetPractice: projects/netpractice.md
    - Philosophers: projects/philosophers.md
    - pipex: projects/pipex.md
    - push_swap: projects/push_swap.md
    - so_long: projects/so_long.md
    - webserv: projects/webserv.md
