site_name: ft_badges
site_url: https://airone01.github.io/ft_badges/
repo_url: https://airone01.github.io/ft_badges/
theme:
  name: shadcn
  icon: lucide:award

docs_dir: markdown_src
site_dir: docs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Projects:
    - Libft: projects/libft.md
    - ft_printf: projects/ft_printf.md
    - Bord2beroot: projects/born2beroot.md
    - get_next_line: projects/get_next_line.md
    - push_swap: projects/push_swap.md
    - minishell: projects/minishell.md
